### ISSUE TITLE
transfomations 

### ISSUE THREAD

**Issue by sadeghjfr** [T8RIN/BlurTransformation#1]
There is no transfomations  in AsyncImage coil!

**Comment by T8RIN** [comment]
Sorry, forgot about it, you can use this github.com/t8rin/coilwrapper repo, or either use imageloader, i'll add this amendment in repo right now

**Comment by T8RIN** [comment]
val request = ImageRequest.Builder(context) 
         .data(model)  
         .transformations(transformations) 
         .build()

**Comment by T8RIN** [comment]
Check repo, i've updated it
